[book]
authors = ["Sebastian Nagel", "Paul Clark"]
language = "en"
multilingual = false
src = "src"
title = "Cardano Blueprint"

[build]
build-dir = "out"

[preprocessor]

[preprocessor.alerts]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]

[output]

[output.html]
additional-js = [".mdbook/mermaid.min.js", ".mdbook/mermaid-init.js"]
smart-punctuation = true
site-url = "/cardano-blueprint/"
git-repository-url = "https://github.com/cardano-scaling/cardano-blueprint/tree/main"
edit-url-template = "https://github.com/cardano-scaling/cardano-blueprint/edit/main/{path}"
